export const ActionTypes = {
  FETCH_MOVIELIST: "FETCH_MOVIELIST",
  FETCH_TVLIST: "FETCH_TVLIST",
  FETCH_TRENDING: "FETCH_TRENDING",
  SELECTED_ITEM: "SELECTED_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SEARCH_ITEM: "SEARCH_ITEM",
  SEARCH_COUNT: "SEARCH_COUNT",
  REMOVE_SEARCH: "REMOVE_SEARCH",
};
